### ISSUE TITLE
Адреса файлстора и писсикаки изменились

### ISSUE THREAD

**Issue by ridouchire** [U-Me-Chan/pissychan-front#48]
Надо поправить.

1. pissykaka.scheoble.xyz -> scheoble.xyz/api
2. filestore.scheoble.xyz -> scheoble.xyz/filestore

Сервисы на поддоменах будут недоступны в ближайшее время.

**Comment by Oxore** [comment]
Надо немного переделывать схему доступа теперь. Пока отключил инстанс чана, некогда.

**Comment by Oxore** [comment]
Починено в https://github.com/U-Me-Chan/pissychan-front/commit/36a1b869211f35fcf5083047449f498a1d23c623.

**Comment by ridouchire** [comment]
ДА ХУЛЕ МЕНЯ СЮДА РЕДИРЕКТИТ РОТ ЕБАЛ АВТОРА И ВСЕХ КТО ТУТ ОБИТАЕТ ГАВНО БЛЯДЬ

**Comment by Oxore** [comment]
Соси кэширование 301 браузером

**Comment by Oxore** [comment]
Больше не буду 301 использовать для редиректов никогда :<
